### ISSUE TITLE
Fully Transparent Header on Issues List

### ISSUE THREAD

**Issue by mccarron** [5calls/ios#63] opened 2017-02-11 16:29 UTC
Not sure why or how this happened, but @nickoneill reported this. 

![pasted image at 2017_02_09 10_37 pm 1](https://cloud.githubusercontent.com/assets/45654/22855346/d1b9cac8-f044-11e6-846b-f9b546d3b32d.png)

I thought it was maybe Transparency turned off in Accessibility but that wasn't it. Hopefully someone has seen similar and can help reproduce this one.

**Comment by nickoneill** [comment] 2017-02-11 20:29
Original reporter doesn't know any other special options turned on, definitely not reduced transparency. It's a SE.

**Comment by mccarron** [comment] 2017-02-11 20:52
@nickoneill Did you find out what iOS version they are on?

**Comment by inuwali** [comment] 2017-02-11 22:09
@mccarron  I'm seeing this on my iPhone 7 running 10.2.1.

There's a difference in the view hierarchy when I run on device versus when I run on sim (seeing proper effect).

Sim: UIVisualEffectView has three subviews: _UIVisualEffectBackdropView, _UIVisualEffectFilterView, _UIVisualEffectContentView

Device: UIVisualEffectView has one subview: _UIVisualEffectContentView

**Comment by mccarron** [comment] 2017-02-12 01:38
@inuwali Does it always happen or is it fixed if you force quit the app?

**Comment by inuwali** [comment] 2017-02-12 15:44
It is 100% reproducible, right from a cold launch. I'm currently trying swapping out the storyboard instance for a programmatic one to see if that has any impact.

**Comment by subdigital** [comment] 2017-02-12 16:28
@inuwali Does this happen as a result of the view swapping animation that happens here? https://github.com/5calls/ios/blob/master/FiveCalls/FiveCalls/AppDelegate.swift#L41

**Comment by mccarron** [comment] 2017-02-12 17:05
@inuwali Also you can try to debug the issue with this command in the debugger: 

`po [visualEffectView _whatsWrongWithThisEffect]`

Source: https://forums.developer.apple.com/message/76154#76153

**Comment by inuwali** [comment] 2017-02-12 19:49
@mccarron Thanks for the tip; unfortunately having trouble as a Swift newbie getting this to work in LLDB. Have tried:

`expr self.headerView._whatsWrongWithThisEffect()`
`expr -l swift -- self.headerView._whatsWrongWithThisEffect()`
`expr -l objC -- [self.headerView _whatsWrongWithThisEffect]`
`expr -l swift -- self.headerView.perform(Selector("_whatsWrongWithThisEffect"))` (this one gives back `(Unmanaged<AnyObject>?) $R2 = (_value = AnyObject @ 0x00007fd9eb017500)` which I can't cast)

**Comment by inuwali** [comment] 2017-02-12 19:49
@subdigital I'll check that to see.

**Comment by inuwali** [comment] 2017-02-12 21:01
@subdigital No; since this happens after first run when that function is never called.

**Comment by inuwali** [comment] 2017-02-12 21:10
@mccarron @subdigital 

Adding these lines to IssuesContainerViewController.viewDidLoad() worked:

`
        let replacement = UIVisualEffectView(frame: self.headerView.frame)
        let contents = (self.headerView as! UIVisualEffectView).contentView.subviews[0]
        contents.removeFromSuperview()
        replacement.contentView.addSubview(contents)
        NSLayoutConstraint.activate([
            replacement.contentView.topAnchor.constraint(equalTo: contents.topAnchor),
            replacement.contentView.bottomAnchor.constraint(equalTo: contents.bottomAnchor),
            replacement.contentView.leftAnchor.constraint(equalTo: contents.leftAnchor),
            replacement.contentView.rightAnchor.constraint(equalTo: contents.rightAnchor)
            ])
        
        replacement.effect = UIBlurEffect(style: .light)
        
        view.insertSubview(replacement, belowSubview: headerView)
        
        NSLayoutConstraint.activate([
            view.topAnchor.constraint(equalTo: replacement.topAnchor),
            view.leftAnchor.constraint(equalTo: replacement.leftAnchor),
            view.rightAnchor.constraint(equalTo: replacement.rightAnchor),
            NSLayoutConstraint(item: replacement, attribute:.height, relatedBy:.equal, toItem:nil, attribute:.notAnAttribute, multiplier:1, constant: 120)
            ])
        
        headerView.removeFromSuperview()
`

**Comment by subdigital** [comment] 2017-02-13 16:42
@inuwali I tried this but get some duplicate constraint warnings.

I think it might be worth moving the visual effect view entirely in code and simply have a 120pt tall container w/ the content view (with logo, location button, etc) defined in the storyboard. Then in viewDidLoad we can wake up and wrap the header view in the effect view.

Do you want to take a stab at this and send a PR?

**Comment by inuwali** [comment] 2017-02-13 18:29
@subdigital 
Yeah, the code I posted was just a trial to see if programmatic implementation would work. I'm happy to work on the solution and submit a PR.

**Comment by inuwali** [comment] 2017-02-18 21:06
PR forthcoming. FYI, I had to reverse one of your recent commits to get things working properly after I merged in the latest from upstream. It's commented.

**Comment by inuwali** [comment] 2017-02-19 19:16
@subdigital @mccarron The PR is up.

**Comment by subdigital** [comment] 2017-02-20 02:32
Closing, tracking on #85.

**Closed by subdigital** 2017-02-20 02:32 UTC
Labels: bug, help wanted
